version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "3000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=porxy.example
    

  website:
    image: dimitribalmer/webserver:latest
    ports: 
      - "8080"
    environment:
      - VIRTUAL_HOST=porxy.example
  
    restart: always